import { getServerSession } from "next-auth";
import Header from "../components/Header";
import LoginComponent from "../components/LoginComponent";
import { SessionProvider } from "../components/SessionProvider";
import { authOptions } from "../pages/api/auth/[...nextauth]";
import "../styles/globals.css";

export const metadata = {
  title: "Messaging app",
  description: "Generated by witty.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <>
              <Header />
              <LoginComponent />
            </>
          ) : (
            <>
              <Header />
              <div className="">{children}</div>
            </>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
